from __future__ import annotations

INVENTORY_FILE_NAME = "migration_inventory.json"
DATASET_PROFILES_FILE_NAME = "dataset_profiles.json"
SCHEMA_INVENTORY_FILE_NAME = "schema_inventory.json"
MAPPING_REVIEW_FILE_NAME = "mapping_review.json"
CONTRACT_REVIEW_FILE_NAME = "contract_review.json"
RECONCILIATION_RESULTS_FILE_NAME = "reconciliation_results.json"
SENSITIVE_FIELD_REVIEW_FILE_NAME = "sensitive_field_review.json"
TEST_EVIDENCE_REVIEW_FILE_NAME = "test_evidence_review.json"
EVIDENCE_COVERAGE_REVIEW_FILE_NAME = "evidence_coverage_review.json"
REVIEW_PACK_FILE_NAME = "review_pack.json"
REVIEWER_SUMMARY_FILE_NAME = "reviewer_summary.md"
LLM_REVIEWER_NOTES_FILE_NAME = "llm_reviewer_notes.json"
TRACE_FILE_NAME = "migration_readiness_trace.json"

ORDERED_ARTIFACT_FILE_NAMES = (
    INVENTORY_FILE_NAME,
    DATASET_PROFILES_FILE_NAME,
    SCHEMA_INVENTORY_FILE_NAME,
    MAPPING_REVIEW_FILE_NAME,
    CONTRACT_REVIEW_FILE_NAME,
    RECONCILIATION_RESULTS_FILE_NAME,
    SENSITIVE_FIELD_REVIEW_FILE_NAME,
    TEST_EVIDENCE_REVIEW_FILE_NAME,
    EVIDENCE_COVERAGE_REVIEW_FILE_NAME,
    REVIEW_PACK_FILE_NAME,
    REVIEWER_SUMMARY_FILE_NAME,
    LLM_REVIEWER_NOTES_FILE_NAME,
    TRACE_FILE_NAME,
)

JSON_ARTIFACT_FILE_NAMES = tuple(
    file_name
    for file_name in ORDERED_ARTIFACT_FILE_NAMES
    if file_name != REVIEWER_SUMMARY_FILE_NAME
)
MARKDOWN_ARTIFACT_FILE_NAMES = (REVIEWER_SUMMARY_FILE_NAME,)
